import {
  Image,
  FileImage,
  Maximize,
  Smartphone,
  Eraser,
  Binary,
  FileType,
  FileText,
  Images,
  Film,
  Braces,
  Code,
  Link,
  Hash,
  Regex,
  KeyRound,
  GitCompare,
  Clock,
  Timer,
  Type,
  Globe,
  Search,
  ShieldCheck,
  Server,
  MapPin,
  Calendar,
  Eye,
  Camera,
  Wifi,
  FileCode,
  Home,
  Activity,
  TrendingUp,
  Percent,
  Cake,
  CreditCard,
  ArrowRightLeft,
  CalendarDays,
  Network,
  Lock,
  QrCode,
  BarChart3,
  Star,
  Paintbrush,
  Palette,
  ImageIcon,
  Fingerprint,
  CaseSensitive,
  FileEdit,
  BookOpen,
  LucideIcon,
  Bot,
  RefreshCw,
  FileSearch,
  SpellCheck,
  Sparkles,
  Flame,
  Dumbbell,
  DollarSign,
  BadgePercent,
  Receipt,
  ScrollText,
  AlignLeft,
  KeySquare,
  Pipette,
  TimerReset,
  Table,
  Database,
  FileDown,
  Wind,
  FileQuestion,
} from "lucide-react";

export type ToolCategory =
  | "AI Tools"
  | "Image Tools"
  | "Developer Tools"
  | "Network Tools"
  | "Calculators"
  | "Generators";

export interface Tool {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: LucideIcon;
  href: string;
  isNew?: boolean;
  isPopular?: boolean;
}

export const categoryConfig: Record<
  ToolCategory,
  { emoji: string; color: string; bgColor: string }
> = {
  "AI Tools": {
    emoji: "🤖",
    color: "text-emerald-400",
    bgColor: "bg-emerald-500/10",
  },
  "Image Tools": {
    emoji: "🖼️",
    color: "text-pink-400",
    bgColor: "bg-pink-500/10",
  },
  "Developer Tools": {
    emoji: "🔧",
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
  },
  "Network Tools": {
    emoji: "🌐",
    color: "text-green-400",
    bgColor: "bg-green-500/10",
  },
  Calculators: {
    emoji: "🧮",
    color: "text-orange-400",
    bgColor: "bg-orange-500/10",
  },
  Generators: {
    emoji: "⚡",
    color: "text-purple-400",
    bgColor: "bg-purple-500/10",
  },
};

export const tools: Tool[] = [
  // AI Tools
  {
    id: "ai-humanizer",
    name: "AI Text Humanizer",
    description: "Make AI-generated text sound natural and human",
    category: "AI Tools",
    icon: Bot,
    href: "/tools/ai-humanizer",
    isNew: true,
    isPopular: true,
  },
  {
    id: "ai-paraphraser",
    name: "AI Paraphraser",
    description: "Rewrite text with different words and style",
    category: "AI Tools",
    icon: RefreshCw,
    href: "/tools/ai-paraphraser",
    isPopular: true,
  },
  {
    id: "ai-summarizer",
    name: "AI Summarizer",
    description: "Summarize long text into key points",
    category: "AI Tools",
    icon: FileSearch,
    href: "/tools/ai-summarizer",
    isNew: true,
  },
  {
    id: "plagiarism-checker",
    name: "Plagiarism Checker",
    description: "Check text for duplicate content",
    category: "AI Tools",
    icon: SpellCheck,
    href: "/tools/plagiarism-checker",
    isPopular: true,
  },
  {
    id: "ai-grammar-checker",
    name: "AI Grammar Checker",
    description: "Fix grammar, spelling, and punctuation errors",
    category: "AI Tools",
    icon: Sparkles,
    href: "/tools/ai-grammar-checker",
    isNew: true,
  },

  // Image Tools
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress images without losing quality",
    category: "Image Tools",
    icon: Image,
    href: "/tools/image-compressor",
    isPopular: true,
  },
  {
    id: "image-converter",
    name: "Image Converter",
    description: "Convert between PNG, JPG, WebP, AVIF",
    category: "Image Tools",
    icon: FileImage,
    href: "/tools/image-converter",
    isPopular: true,
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize images to exact dimensions",
    category: "Image Tools",
    icon: Maximize,
    href: "/tools/image-resizer",
  },
  {
    id: "heic-to-jpg",
    name: "HEIC to JPG",
    description: "Convert iPhone HEIC photos to JPG",
    category: "Image Tools",
    icon: Smartphone,
    href: "/tools/heic-to-jpg",
    isNew: true,
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove image backgrounds instantly",
    category: "Image Tools",
    icon: Eraser,
    href: "/tools/background-remover",
    isPopular: true,
  },
  {
    id: "image-to-base64",
    name: "Image to Base64",
    description: "Convert images to Base64 string",
    category: "Image Tools",
    icon: Binary,
    href: "/tools/image-to-base64",
  },
  {
    id: "svg-to-png",
    name: "SVG to PNG",
    description: "Convert SVG vectors to PNG",
    category: "Image Tools",
    icon: FileType,
    href: "/tools/svg-to-png",
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    description: "Convert PDF pages to images",
    category: "Image Tools",
    icon: FileText,
    href: "/tools/pdf-to-image",
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    description: "Create PDF from images",
    category: "Image Tools",
    icon: Images,
    href: "/tools/image-to-pdf",
  },
  {
    id: "video-to-gif",
    name: "Video to GIF",
    description: "Convert video clips to GIF",
    category: "Image Tools",
    icon: Film,
    href: "/tools/video-to-gif",
    isNew: true,
  },

  // Developer Tools
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format and validate JSON",
    category: "Developer Tools",
    icon: Braces,
    href: "/tools/json-formatter",
    isPopular: true,
  },
  {
    id: "base64",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode Base64",
    category: "Developer Tools",
    icon: Code,
    href: "/tools/base64",
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "URL encode and decode strings",
    category: "Developer Tools",
    icon: Link,
    href: "/tools/url-encoder",
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA1, SHA256 hashes",
    category: "Developer Tools",
    icon: Hash,
    href: "/tools/hash-generator",
    isPopular: true,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions with live matching",
    category: "Developer Tools",
    icon: Regex,
    href: "/tools/regex-tester",
    isPopular: true,
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JWT tokens",
    category: "Developer Tools",
    icon: KeyRound,
    href: "/tools/jwt-decoder",
  },
  {
    id: "code-diff",
    name: "Code Diff",
    description: "Compare two code blocks side by side",
    category: "Developer Tools",
    icon: GitCompare,
    href: "/tools/code-diff",
  },
  {
    id: "cron-parser",
    name: "Cron Parser",
    description: "Parse and explain cron expressions",
    category: "Developer Tools",
    icon: Clock,
    href: "/tools/cron-parser",
  },
  {
    id: "unix-timestamp",
    name: "Unix Timestamp",
    description: "Convert Unix timestamps to dates",
    category: "Developer Tools",
    icon: Timer,
    href: "/tools/unix-timestamp",
  },
  {
    id: "html-entities",
    name: "HTML Entities",
    description: "Encode and decode HTML entities",
    category: "Developer Tools",
    icon: Type,
    href: "/tools/html-entities",
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV",
    description: "Convert JSON data to CSV format",
    category: "Developer Tools",
    icon: Table,
    href: "/tools/json-to-csv",
    isNew: true,
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries",
    category: "Developer Tools",
    icon: Database,
    href: "/tools/sql-formatter",
    isNew: true,
  },
  {
    id: "html-to-markdown",
    name: "HTML to Markdown",
    description: "Convert HTML to Markdown format",
    category: "Developer Tools",
    icon: FileDown,
    href: "/tools/html-to-markdown",
    isNew: true,
  },
  {
    id: "tailwind-playground",
    name: "Tailwind CSS Playground",
    description: "Preview Tailwind CSS classes in real time",
    category: "Developer Tools",
    icon: Wind,
    href: "/tools/tailwind-playground",
    isNew: true,
    isPopular: true,
  },

  // Network Tools
  {
    id: "dns-lookup",
    name: "DNS Lookup",
    description: "Look up DNS records for any domain",
    category: "Network Tools",
    icon: Globe,
    href: "/tools/dns-lookup",
  },
  {
    id: "whois-lookup",
    name: "WHOIS Lookup",
    description: "Get domain registration information",
    category: "Network Tools",
    icon: Search,
    href: "/tools/whois-lookup",
  },
  {
    id: "ssl-checker",
    name: "SSL Checker",
    description: "Check SSL certificate details",
    category: "Network Tools",
    icon: ShieldCheck,
    href: "/tools/ssl-checker",
  },
  {
    id: "http-headers",
    name: "HTTP Headers",
    description: "Inspect HTTP response headers",
    category: "Network Tools",
    icon: Server,
    href: "/tools/http-headers",
  },
  {
    id: "ip-lookup",
    name: "IP Lookup",
    description: "Get geolocation for any IP address",
    category: "Network Tools",
    icon: MapPin,
    href: "/tools/ip-lookup",
  },
  {
    id: "domain-age",
    name: "Domain Age",
    description: "Check when a domain was registered",
    category: "Network Tools",
    icon: Calendar,
    href: "/tools/domain-age",
  },
  {
    id: "open-graph-preview",
    name: "Open Graph Preview",
    description: "Preview Open Graph meta tags",
    category: "Network Tools",
    icon: Eye,
    href: "/tools/open-graph-preview",
  },
  {
    id: "website-screenshot",
    name: "Website Screenshot",
    description: "Capture screenshots of websites",
    category: "Network Tools",
    icon: Camera,
    href: "/tools/website-screenshot",
  },
  {
    id: "port-checker",
    name: "Port Checker",
    description: "Check if a port is open",
    category: "Network Tools",
    icon: Wifi,
    href: "/tools/port-checker",
  },
  {
    id: "sitemap-generator",
    name: "Sitemap Generator",
    description: "Generate XML sitemap for websites",
    category: "Network Tools",
    icon: FileCode,
    href: "/tools/sitemap-generator",
  },
  {
    id: "robots-txt-generator",
    name: "Robots.txt Generator",
    description: "Generate robots.txt file for SEO",
    category: "Network Tools",
    icon: FileQuestion,
    href: "/tools/robots-txt-generator",
    isNew: true,
  },

  // Calculators
  {
    id: "mortgage-calculator",
    name: "Mortgage Calculator",
    description: "Calculate monthly mortgage payments",
    category: "Calculators",
    icon: Home,
    href: "/tools/mortgage-calculator",
    isPopular: true,
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate Body Mass Index",
    category: "Calculators",
    icon: Activity,
    href: "/tools/bmi-calculator",
  },
  {
    id: "compound-interest",
    name: "Compound Interest",
    description: "Calculate compound interest growth",
    category: "Calculators",
    icon: TrendingUp,
    href: "/tools/compound-interest",
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages instantly",
    category: "Calculators",
    icon: Percent,
    href: "/tools/percentage-calculator",
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    description: "Calculate exact age from birthdate",
    category: "Calculators",
    icon: Cake,
    href: "/tools/age-calculator",
  },
  {
    id: "loan-emi",
    name: "Loan EMI Calculator",
    description: "Calculate loan EMI and amortization",
    category: "Calculators",
    icon: CreditCard,
    href: "/tools/loan-emi",
  },
  {
    id: "time-zone-converter",
    name: "Time Zone Converter",
    description: "Convert times across time zones",
    category: "Calculators",
    icon: ArrowRightLeft,
    href: "/tools/time-zone-converter",
  },
  {
    id: "date-difference",
    name: "Date Difference",
    description: "Calculate days between two dates",
    category: "Calculators",
    icon: CalendarDays,
    href: "/tools/date-difference",
  },
  {
    id: "subnet-calculator",
    name: "Subnet Calculator",
    description: "Calculate IP subnet ranges",
    category: "Calculators",
    icon: Network,
    href: "/tools/subnet-calculator",
  },
  {
    id: "password-strength",
    name: "Password Strength",
    description: "Check password strength and entropy",
    category: "Calculators",
    icon: Lock,
    href: "/tools/password-strength",
  },
  {
    id: "calorie-calculator",
    name: "Calorie Calculator",
    description: "Calculate daily calorie needs and macros",
    category: "Calculators",
    icon: Flame,
    href: "/tools/calorie-calculator",
    isNew: true,
    isPopular: true,
  },
  {
    id: "tdee-calculator",
    name: "TDEE Calculator",
    description: "Calculate Total Daily Energy Expenditure",
    category: "Calculators",
    icon: Dumbbell,
    href: "/tools/tdee-calculator",
    isNew: true,
  },
  {
    id: "salary-calculator",
    name: "Salary Calculator",
    description: "Convert salary between hourly, monthly, yearly",
    category: "Calculators",
    icon: DollarSign,
    href: "/tools/salary-calculator",
    isNew: true,
  },
  {
    id: "discount-calculator",
    name: "Discount Calculator",
    description: "Calculate discount price and savings",
    category: "Calculators",
    icon: BadgePercent,
    href: "/tools/discount-calculator",
    isNew: true,
  },

  // Generators
  {
    id: "qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for any text or URL",
    category: "Generators",
    icon: QrCode,
    href: "/tools/qr-generator",
    isPopular: true,
  },
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate barcodes in multiple formats",
    category: "Generators",
    icon: BarChart3,
    href: "/tools/barcode-generator",
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "Create favicons from images or text",
    category: "Generators",
    icon: Star,
    href: "/tools/favicon-generator",
  },
  {
    id: "css-gradient",
    name: "CSS Gradient Generator",
    description: "Create beautiful CSS gradients visually",
    category: "Generators",
    icon: Paintbrush,
    href: "/tools/css-gradient",
    isNew: true,
  },
  {
    id: "color-palette",
    name: "Color Palette",
    description: "Extract color palettes from images",
    category: "Generators",
    icon: Palette,
    href: "/tools/color-palette",
  },
  {
    id: "placeholder-image",
    name: "Placeholder Image",
    description: "Generate placeholder images for mockups",
    category: "Generators",
    icon: ImageIcon,
    href: "/tools/placeholder-image",
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate UUIDs and random strings",
    category: "Generators",
    icon: Fingerprint,
    href: "/tools/uuid-generator",
  },
  {
    id: "text-case-converter",
    name: "Text Case Converter",
    description: "Convert text between cases",
    category: "Generators",
    icon: CaseSensitive,
    href: "/tools/text-case-converter",
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, and reading time",
    category: "Generators",
    icon: FileEdit,
    href: "/tools/word-counter",
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Preview Markdown with live rendering",
    category: "Generators",
    icon: BookOpen,
    href: "/tools/markdown-preview",
  },
  {
    id: "invoice-generator",
    name: "Invoice Generator",
    description: "Create professional invoices in PDF",
    category: "Generators",
    icon: Receipt,
    href: "/tools/invoice-generator",
    isNew: true,
    isPopular: true,
  },
  {
    id: "privacy-policy-generator",
    name: "Privacy Policy Generator",
    description: "Generate privacy policy for your website",
    category: "Generators",
    icon: ScrollText,
    href: "/tools/privacy-policy-generator",
    isNew: true,
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for designs",
    category: "Generators",
    icon: AlignLeft,
    href: "/tools/lorem-ipsum-generator",
    isNew: true,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate strong random passwords",
    category: "Generators",
    icon: KeySquare,
    href: "/tools/password-generator",
    isNew: true,
    isPopular: true,
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Pick colors and convert between formats",
    category: "Generators",
    icon: Pipette,
    href: "/tools/color-picker",
    isNew: true,
  },
  {
    id: "pomodoro-timer",
    name: "Pomodoro Timer",
    description: "Focus timer with work and break intervals",
    category: "Generators",
    icon: TimerReset,
    href: "/tools/pomodoro-timer",
    isNew: true,
  },
];

export const categories = Object.keys(categoryConfig) as ToolCategory[];

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id);
}
